namespace QLCH_CameraADC
{
    partial class frmMeNu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMeNu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btnThoat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThongKe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNhapHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBanHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSanPham = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLoaiSP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNhaCungCap = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnKhachHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNhanVien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelTop = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panelBottom = new System.Windows.Forms.Panel();
            this.panelMid = new System.Windows.Forms.Panel();
            this.btnQLHoaDon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panelTop.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Controls.Add(this.btnThoat);
            this.panel1.Controls.Add(this.btnThongKe);
            this.panel1.Controls.Add(this.btnQLHoaDon);
            this.panel1.Controls.Add(this.btnNhapHang);
            this.panel1.Controls.Add(this.btnBanHang);
            this.panel1.Controls.Add(this.btnSanPham);
            this.panel1.Controls.Add(this.btnLoaiSP);
            this.panel1.Controls.Add(this.btnNhaCungCap);
            this.panel1.Controls.Add(this.btnKhachHang);
            this.panel1.Controls.Add(this.btnNhanVien);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(293, 1027);
            this.panel1.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImage = global::QLCH_CameraADC.Properties.Resources.logo_adc_group;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(293, 151);
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // btnThoat
            // 
            this.btnThoat.AllowAnimations = true;
            this.btnThoat.AllowMouseEffects = true;
            this.btnThoat.AllowToggling = true;
            this.btnThoat.AnimationSpeed = 200;
            this.btnThoat.AutoGenerateColors = false;
            this.btnThoat.AutoRoundBorders = false;
            this.btnThoat.AutoSizeLeftIcon = true;
            this.btnThoat.AutoSizeRightIcon = true;
            this.btnThoat.BackColor = System.Drawing.Color.Transparent;
            this.btnThoat.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThoat.BackgroundImage")));
            this.btnThoat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.ButtonText = "Thoát";
            this.btnThoat.ButtonTextMarginLeft = 0;
            this.btnThoat.ColorContrastOnClick = 45;
            this.btnThoat.ColorContrastOnHover = 45;
            this.btnThoat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnThoat.CustomizableEdges = borderEdges11;
            this.btnThoat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThoat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThoat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThoat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThoat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThoat.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThoat.ForeColor = System.Drawing.Color.White;
            this.btnThoat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThoat.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThoat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThoat.IconMarginLeft = 11;
            this.btnThoat.IconPadding = 10;
            this.btnThoat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThoat.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThoat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThoat.IconSize = 25;
            this.btnThoat.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.IdleBorderRadius = 30;
            this.btnThoat.IdleBorderThickness = 1;
            this.btnThoat.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.IdleIconLeftImage = null;
            this.btnThoat.IdleIconRightImage = null;
            this.btnThoat.IndicateFocus = true;
            this.btnThoat.Location = new System.Drawing.Point(40, 957);
            this.btnThoat.Name = "btnThoat";
            this.btnThoat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThoat.OnDisabledState.BorderRadius = 30;
            this.btnThoat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnDisabledState.BorderThickness = 1;
            this.btnThoat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThoat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThoat.OnDisabledState.IconLeftImage = null;
            this.btnThoat.OnDisabledState.IconRightImage = null;
            this.btnThoat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.onHoverState.BorderRadius = 30;
            this.btnThoat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.onHoverState.BorderThickness = 1;
            this.btnThoat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnThoat.onHoverState.IconLeftImage = null;
            this.btnThoat.onHoverState.IconRightImage = null;
            this.btnThoat.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.OnIdleState.BorderRadius = 30;
            this.btnThoat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnIdleState.BorderThickness = 1;
            this.btnThoat.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThoat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThoat.OnIdleState.IconLeftImage = null;
            this.btnThoat.OnIdleState.IconRightImage = null;
            this.btnThoat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnThoat.OnPressedState.BorderRadius = 30;
            this.btnThoat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnPressedState.BorderThickness = 1;
            this.btnThoat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnThoat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThoat.OnPressedState.IconLeftImage = null;
            this.btnThoat.OnPressedState.IconRightImage = null;
            this.btnThoat.Size = new System.Drawing.Size(211, 58);
            this.btnThoat.TabIndex = 0;
            this.btnThoat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThoat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThoat.TextMarginLeft = 0;
            this.btnThoat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThoat.UseDefaultRadiusAndThickness = true;
            this.btnThoat.Click += new System.EventHandler(this.btnThoat_Click);
            // 
            // btnThongKe
            // 
            this.btnThongKe.AllowAnimations = true;
            this.btnThongKe.AllowMouseEffects = true;
            this.btnThongKe.AllowToggling = true;
            this.btnThongKe.AnimationSpeed = 200;
            this.btnThongKe.AutoGenerateColors = false;
            this.btnThongKe.AutoRoundBorders = false;
            this.btnThongKe.AutoSizeLeftIcon = true;
            this.btnThongKe.AutoSizeRightIcon = true;
            this.btnThongKe.BackColor = System.Drawing.Color.Transparent;
            this.btnThongKe.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThongKe.BackgroundImage")));
            this.btnThongKe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.ButtonText = "Thống kê";
            this.btnThongKe.ButtonTextMarginLeft = 0;
            this.btnThongKe.ColorContrastOnClick = 45;
            this.btnThongKe.ColorContrastOnHover = 45;
            this.btnThongKe.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnThongKe.CustomizableEdges = borderEdges12;
            this.btnThongKe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThongKe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongKe.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongKe.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongKe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThongKe.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThongKe.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongKe.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThongKe.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThongKe.IconMarginLeft = 11;
            this.btnThongKe.IconPadding = 10;
            this.btnThongKe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThongKe.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThongKe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThongKe.IconSize = 25;
            this.btnThongKe.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.IdleBorderRadius = 30;
            this.btnThongKe.IdleBorderThickness = 1;
            this.btnThongKe.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.IdleIconLeftImage = null;
            this.btnThongKe.IdleIconRightImage = null;
            this.btnThongKe.IndicateFocus = true;
            this.btnThongKe.Location = new System.Drawing.Point(40, 864);
            this.btnThongKe.Name = "btnThongKe";
            this.btnThongKe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongKe.OnDisabledState.BorderRadius = 30;
            this.btnThongKe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnDisabledState.BorderThickness = 1;
            this.btnThongKe.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongKe.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongKe.OnDisabledState.IconLeftImage = null;
            this.btnThongKe.OnDisabledState.IconRightImage = null;
            this.btnThongKe.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.onHoverState.BorderRadius = 30;
            this.btnThongKe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.onHoverState.BorderThickness = 1;
            this.btnThongKe.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnThongKe.onHoverState.IconLeftImage = null;
            this.btnThongKe.onHoverState.IconRightImage = null;
            this.btnThongKe.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.OnIdleState.BorderRadius = 30;
            this.btnThongKe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnIdleState.BorderThickness = 1;
            this.btnThongKe.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnThongKe.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.OnIdleState.IconLeftImage = null;
            this.btnThongKe.OnIdleState.IconRightImage = null;
            this.btnThongKe.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnThongKe.OnPressedState.BorderRadius = 30;
            this.btnThongKe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnPressedState.BorderThickness = 1;
            this.btnThongKe.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnThongKe.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.OnPressedState.IconLeftImage = null;
            this.btnThongKe.OnPressedState.IconRightImage = null;
            this.btnThongKe.Size = new System.Drawing.Size(211, 58);
            this.btnThongKe.TabIndex = 0;
            this.btnThongKe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThongKe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThongKe.TextMarginLeft = 0;
            this.btnThongKe.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThongKe.UseDefaultRadiusAndThickness = true;
            // 
            // btnNhapHang
            // 
            this.btnNhapHang.AllowAnimations = true;
            this.btnNhapHang.AllowMouseEffects = true;
            this.btnNhapHang.AllowToggling = true;
            this.btnNhapHang.AnimationSpeed = 200;
            this.btnNhapHang.AutoGenerateColors = false;
            this.btnNhapHang.AutoRoundBorders = false;
            this.btnNhapHang.AutoSizeLeftIcon = true;
            this.btnNhapHang.AutoSizeRightIcon = true;
            this.btnNhapHang.BackColor = System.Drawing.Color.Transparent;
            this.btnNhapHang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNhapHang.BackgroundImage")));
            this.btnNhapHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.ButtonText = "Nhập hàng";
            this.btnNhapHang.ButtonTextMarginLeft = 0;
            this.btnNhapHang.ColorContrastOnClick = 45;
            this.btnNhapHang.ColorContrastOnHover = 45;
            this.btnNhapHang.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnNhapHang.CustomizableEdges = borderEdges13;
            this.btnNhapHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNhapHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhapHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhapHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhapHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNhapHang.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNhapHang.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNhapHang.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhapHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNhapHang.IconMarginLeft = 11;
            this.btnNhapHang.IconPadding = 10;
            this.btnNhapHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNhapHang.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhapHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNhapHang.IconSize = 25;
            this.btnNhapHang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.IdleBorderRadius = 30;
            this.btnNhapHang.IdleBorderThickness = 1;
            this.btnNhapHang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.IdleIconLeftImage = null;
            this.btnNhapHang.IdleIconRightImage = null;
            this.btnNhapHang.IndicateFocus = true;
            this.btnNhapHang.Location = new System.Drawing.Point(40, 718);
            this.btnNhapHang.Name = "btnNhapHang";
            this.btnNhapHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhapHang.OnDisabledState.BorderRadius = 30;
            this.btnNhapHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnDisabledState.BorderThickness = 1;
            this.btnNhapHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhapHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhapHang.OnDisabledState.IconLeftImage = null;
            this.btnNhapHang.OnDisabledState.IconRightImage = null;
            this.btnNhapHang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.onHoverState.BorderRadius = 30;
            this.btnNhapHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.onHoverState.BorderThickness = 1;
            this.btnNhapHang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnNhapHang.onHoverState.IconLeftImage = null;
            this.btnNhapHang.onHoverState.IconRightImage = null;
            this.btnNhapHang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.OnIdleState.BorderRadius = 30;
            this.btnNhapHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnIdleState.BorderThickness = 1;
            this.btnNhapHang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhapHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.OnIdleState.IconLeftImage = null;
            this.btnNhapHang.OnIdleState.IconRightImage = null;
            this.btnNhapHang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhapHang.OnPressedState.BorderRadius = 30;
            this.btnNhapHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnPressedState.BorderThickness = 1;
            this.btnNhapHang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhapHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.OnPressedState.IconLeftImage = null;
            this.btnNhapHang.OnPressedState.IconRightImage = null;
            this.btnNhapHang.Size = new System.Drawing.Size(211, 58);
            this.btnNhapHang.TabIndex = 0;
            this.btnNhapHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNhapHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNhapHang.TextMarginLeft = 0;
            this.btnNhapHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNhapHang.UseDefaultRadiusAndThickness = true;
            this.btnNhapHang.Click += new System.EventHandler(this.btnNhapHang_Click);
            // 
            // btnBanHang
            // 
            this.btnBanHang.AllowAnimations = true;
            this.btnBanHang.AllowMouseEffects = true;
            this.btnBanHang.AllowToggling = true;
            this.btnBanHang.AnimationSpeed = 200;
            this.btnBanHang.AutoGenerateColors = false;
            this.btnBanHang.AutoRoundBorders = false;
            this.btnBanHang.AutoSizeLeftIcon = true;
            this.btnBanHang.AutoSizeRightIcon = true;
            this.btnBanHang.BackColor = System.Drawing.Color.Transparent;
            this.btnBanHang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBanHang.BackgroundImage")));
            this.btnBanHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.ButtonText = "Bán hàng";
            this.btnBanHang.ButtonTextMarginLeft = 0;
            this.btnBanHang.ColorContrastOnClick = 45;
            this.btnBanHang.ColorContrastOnHover = 45;
            this.btnBanHang.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnBanHang.CustomizableEdges = borderEdges14;
            this.btnBanHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBanHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBanHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBanHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBanHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBanHang.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBanHang.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBanHang.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnBanHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBanHang.IconMarginLeft = 11;
            this.btnBanHang.IconPadding = 10;
            this.btnBanHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBanHang.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnBanHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBanHang.IconSize = 25;
            this.btnBanHang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.IdleBorderRadius = 30;
            this.btnBanHang.IdleBorderThickness = 1;
            this.btnBanHang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.IdleIconLeftImage = null;
            this.btnBanHang.IdleIconRightImage = null;
            this.btnBanHang.IndicateFocus = true;
            this.btnBanHang.Location = new System.Drawing.Point(40, 645);
            this.btnBanHang.Name = "btnBanHang";
            this.btnBanHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBanHang.OnDisabledState.BorderRadius = 30;
            this.btnBanHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnDisabledState.BorderThickness = 1;
            this.btnBanHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBanHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBanHang.OnDisabledState.IconLeftImage = null;
            this.btnBanHang.OnDisabledState.IconRightImage = null;
            this.btnBanHang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.onHoverState.BorderRadius = 30;
            this.btnBanHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.onHoverState.BorderThickness = 1;
            this.btnBanHang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnBanHang.onHoverState.IconLeftImage = null;
            this.btnBanHang.onHoverState.IconRightImage = null;
            this.btnBanHang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.OnIdleState.BorderRadius = 30;
            this.btnBanHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnIdleState.BorderThickness = 1;
            this.btnBanHang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnBanHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.OnIdleState.IconLeftImage = null;
            this.btnBanHang.OnIdleState.IconRightImage = null;
            this.btnBanHang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnBanHang.OnPressedState.BorderRadius = 30;
            this.btnBanHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnPressedState.BorderThickness = 1;
            this.btnBanHang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnBanHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.OnPressedState.IconLeftImage = null;
            this.btnBanHang.OnPressedState.IconRightImage = null;
            this.btnBanHang.Size = new System.Drawing.Size(211, 58);
            this.btnBanHang.TabIndex = 0;
            this.btnBanHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBanHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBanHang.TextMarginLeft = 0;
            this.btnBanHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBanHang.UseDefaultRadiusAndThickness = true;
            this.btnBanHang.Click += new System.EventHandler(this.btnBanHang_Click);
            // 
            // btnSanPham
            // 
            this.btnSanPham.AllowAnimations = true;
            this.btnSanPham.AllowMouseEffects = true;
            this.btnSanPham.AllowToggling = true;
            this.btnSanPham.AnimationSpeed = 200;
            this.btnSanPham.AutoGenerateColors = false;
            this.btnSanPham.AutoRoundBorders = false;
            this.btnSanPham.AutoSizeLeftIcon = true;
            this.btnSanPham.AutoSizeRightIcon = true;
            this.btnSanPham.BackColor = System.Drawing.Color.Transparent;
            this.btnSanPham.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSanPham.BackgroundImage")));
            this.btnSanPham.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.ButtonText = "Sản phẩm";
            this.btnSanPham.ButtonTextMarginLeft = 0;
            this.btnSanPham.ColorContrastOnClick = 45;
            this.btnSanPham.ColorContrastOnHover = 45;
            this.btnSanPham.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnSanPham.CustomizableEdges = borderEdges15;
            this.btnSanPham.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSanPham.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSanPham.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSanPham.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSanPham.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSanPham.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSanPham.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSanPham.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSanPham.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSanPham.IconMarginLeft = 11;
            this.btnSanPham.IconPadding = 10;
            this.btnSanPham.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSanPham.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSanPham.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSanPham.IconSize = 25;
            this.btnSanPham.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.IdleBorderRadius = 30;
            this.btnSanPham.IdleBorderThickness = 1;
            this.btnSanPham.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.IdleIconLeftImage = null;
            this.btnSanPham.IdleIconRightImage = null;
            this.btnSanPham.IndicateFocus = true;
            this.btnSanPham.Location = new System.Drawing.Point(40, 562);
            this.btnSanPham.Name = "btnSanPham";
            this.btnSanPham.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSanPham.OnDisabledState.BorderRadius = 30;
            this.btnSanPham.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnDisabledState.BorderThickness = 1;
            this.btnSanPham.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSanPham.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSanPham.OnDisabledState.IconLeftImage = null;
            this.btnSanPham.OnDisabledState.IconRightImage = null;
            this.btnSanPham.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.onHoverState.BorderRadius = 30;
            this.btnSanPham.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.onHoverState.BorderThickness = 1;
            this.btnSanPham.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnSanPham.onHoverState.IconLeftImage = null;
            this.btnSanPham.onHoverState.IconRightImage = null;
            this.btnSanPham.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.OnIdleState.BorderRadius = 30;
            this.btnSanPham.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnIdleState.BorderThickness = 1;
            this.btnSanPham.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnSanPham.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.OnIdleState.IconLeftImage = null;
            this.btnSanPham.OnIdleState.IconRightImage = null;
            this.btnSanPham.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnSanPham.OnPressedState.BorderRadius = 30;
            this.btnSanPham.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnPressedState.BorderThickness = 1;
            this.btnSanPham.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnSanPham.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.OnPressedState.IconLeftImage = null;
            this.btnSanPham.OnPressedState.IconRightImage = null;
            this.btnSanPham.Size = new System.Drawing.Size(211, 58);
            this.btnSanPham.TabIndex = 0;
            this.btnSanPham.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSanPham.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSanPham.TextMarginLeft = 0;
            this.btnSanPham.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSanPham.UseDefaultRadiusAndThickness = true;
            this.btnSanPham.Click += new System.EventHandler(this.btnSanPham_Click);
            // 
            // btnLoaiSP
            // 
            this.btnLoaiSP.AllowAnimations = true;
            this.btnLoaiSP.AllowMouseEffects = true;
            this.btnLoaiSP.AllowToggling = true;
            this.btnLoaiSP.AnimationSpeed = 200;
            this.btnLoaiSP.AutoGenerateColors = false;
            this.btnLoaiSP.AutoRoundBorders = false;
            this.btnLoaiSP.AutoSizeLeftIcon = true;
            this.btnLoaiSP.AutoSizeRightIcon = true;
            this.btnLoaiSP.BackColor = System.Drawing.Color.Transparent;
            this.btnLoaiSP.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLoaiSP.BackgroundImage")));
            this.btnLoaiSP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoaiSP.ButtonText = "Loại sản phẩm";
            this.btnLoaiSP.ButtonTextMarginLeft = 0;
            this.btnLoaiSP.ColorContrastOnClick = 45;
            this.btnLoaiSP.ColorContrastOnHover = 45;
            this.btnLoaiSP.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.btnLoaiSP.CustomizableEdges = borderEdges16;
            this.btnLoaiSP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLoaiSP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoaiSP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoaiSP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoaiSP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLoaiSP.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLoaiSP.ForeColor = System.Drawing.Color.White;
            this.btnLoaiSP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLoaiSP.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLoaiSP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLoaiSP.IconMarginLeft = 11;
            this.btnLoaiSP.IconPadding = 10;
            this.btnLoaiSP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLoaiSP.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLoaiSP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLoaiSP.IconSize = 25;
            this.btnLoaiSP.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.IdleBorderRadius = 30;
            this.btnLoaiSP.IdleBorderThickness = 1;
            this.btnLoaiSP.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.IdleIconLeftImage = null;
            this.btnLoaiSP.IdleIconRightImage = null;
            this.btnLoaiSP.IndicateFocus = true;
            this.btnLoaiSP.Location = new System.Drawing.Point(40, 479);
            this.btnLoaiSP.Name = "btnLoaiSP";
            this.btnLoaiSP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLoaiSP.OnDisabledState.BorderRadius = 30;
            this.btnLoaiSP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoaiSP.OnDisabledState.BorderThickness = 1;
            this.btnLoaiSP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLoaiSP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLoaiSP.OnDisabledState.IconLeftImage = null;
            this.btnLoaiSP.OnDisabledState.IconRightImage = null;
            this.btnLoaiSP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.onHoverState.BorderRadius = 30;
            this.btnLoaiSP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoaiSP.onHoverState.BorderThickness = 1;
            this.btnLoaiSP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnLoaiSP.onHoverState.IconLeftImage = null;
            this.btnLoaiSP.onHoverState.IconRightImage = null;
            this.btnLoaiSP.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.OnIdleState.BorderRadius = 30;
            this.btnLoaiSP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoaiSP.OnIdleState.BorderThickness = 1;
            this.btnLoaiSP.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnLoaiSP.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLoaiSP.OnIdleState.IconLeftImage = null;
            this.btnLoaiSP.OnIdleState.IconRightImage = null;
            this.btnLoaiSP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnLoaiSP.OnPressedState.BorderRadius = 30;
            this.btnLoaiSP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLoaiSP.OnPressedState.BorderThickness = 1;
            this.btnLoaiSP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnLoaiSP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLoaiSP.OnPressedState.IconLeftImage = null;
            this.btnLoaiSP.OnPressedState.IconRightImage = null;
            this.btnLoaiSP.Size = new System.Drawing.Size(211, 58);
            this.btnLoaiSP.TabIndex = 0;
            this.btnLoaiSP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLoaiSP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLoaiSP.TextMarginLeft = 0;
            this.btnLoaiSP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLoaiSP.UseDefaultRadiusAndThickness = true;
            this.btnLoaiSP.Click += new System.EventHandler(this.btnLoaiSP_Click);
            // 
            // btnNhaCungCap
            // 
            this.btnNhaCungCap.AllowAnimations = true;
            this.btnNhaCungCap.AllowMouseEffects = true;
            this.btnNhaCungCap.AllowToggling = true;
            this.btnNhaCungCap.AnimationSpeed = 200;
            this.btnNhaCungCap.AutoGenerateColors = false;
            this.btnNhaCungCap.AutoRoundBorders = false;
            this.btnNhaCungCap.AutoSizeLeftIcon = true;
            this.btnNhaCungCap.AutoSizeRightIcon = true;
            this.btnNhaCungCap.BackColor = System.Drawing.Color.Transparent;
            this.btnNhaCungCap.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNhaCungCap.BackgroundImage")));
            this.btnNhaCungCap.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhaCungCap.ButtonText = "Nhà cung cấp";
            this.btnNhaCungCap.ButtonTextMarginLeft = 0;
            this.btnNhaCungCap.ColorContrastOnClick = 45;
            this.btnNhaCungCap.ColorContrastOnHover = 45;
            this.btnNhaCungCap.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges17.BottomLeft = true;
            borderEdges17.BottomRight = true;
            borderEdges17.TopLeft = true;
            borderEdges17.TopRight = true;
            this.btnNhaCungCap.CustomizableEdges = borderEdges17;
            this.btnNhaCungCap.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNhaCungCap.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhaCungCap.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhaCungCap.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhaCungCap.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNhaCungCap.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNhaCungCap.ForeColor = System.Drawing.Color.White;
            this.btnNhaCungCap.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNhaCungCap.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhaCungCap.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNhaCungCap.IconMarginLeft = 11;
            this.btnNhaCungCap.IconPadding = 10;
            this.btnNhaCungCap.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNhaCungCap.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhaCungCap.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNhaCungCap.IconSize = 25;
            this.btnNhaCungCap.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.IdleBorderRadius = 30;
            this.btnNhaCungCap.IdleBorderThickness = 1;
            this.btnNhaCungCap.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.IdleIconLeftImage = null;
            this.btnNhaCungCap.IdleIconRightImage = null;
            this.btnNhaCungCap.IndicateFocus = true;
            this.btnNhaCungCap.Location = new System.Drawing.Point(40, 396);
            this.btnNhaCungCap.Name = "btnNhaCungCap";
            this.btnNhaCungCap.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhaCungCap.OnDisabledState.BorderRadius = 30;
            this.btnNhaCungCap.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhaCungCap.OnDisabledState.BorderThickness = 1;
            this.btnNhaCungCap.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhaCungCap.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhaCungCap.OnDisabledState.IconLeftImage = null;
            this.btnNhaCungCap.OnDisabledState.IconRightImage = null;
            this.btnNhaCungCap.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.onHoverState.BorderRadius = 30;
            this.btnNhaCungCap.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhaCungCap.onHoverState.BorderThickness = 1;
            this.btnNhaCungCap.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnNhaCungCap.onHoverState.IconLeftImage = null;
            this.btnNhaCungCap.onHoverState.IconRightImage = null;
            this.btnNhaCungCap.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.OnIdleState.BorderRadius = 30;
            this.btnNhaCungCap.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhaCungCap.OnIdleState.BorderThickness = 1;
            this.btnNhaCungCap.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhaCungCap.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNhaCungCap.OnIdleState.IconLeftImage = null;
            this.btnNhaCungCap.OnIdleState.IconRightImage = null;
            this.btnNhaCungCap.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhaCungCap.OnPressedState.BorderRadius = 30;
            this.btnNhaCungCap.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhaCungCap.OnPressedState.BorderThickness = 1;
            this.btnNhaCungCap.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhaCungCap.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNhaCungCap.OnPressedState.IconLeftImage = null;
            this.btnNhaCungCap.OnPressedState.IconRightImage = null;
            this.btnNhaCungCap.Size = new System.Drawing.Size(211, 58);
            this.btnNhaCungCap.TabIndex = 0;
            this.btnNhaCungCap.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNhaCungCap.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNhaCungCap.TextMarginLeft = 0;
            this.btnNhaCungCap.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNhaCungCap.UseDefaultRadiusAndThickness = true;
            this.btnNhaCungCap.Click += new System.EventHandler(this.btnNhaCungCap_Click);
            // 
            // btnKhachHang
            // 
            this.btnKhachHang.AllowAnimations = true;
            this.btnKhachHang.AllowMouseEffects = true;
            this.btnKhachHang.AllowToggling = true;
            this.btnKhachHang.AnimationSpeed = 200;
            this.btnKhachHang.AutoGenerateColors = false;
            this.btnKhachHang.AutoRoundBorders = false;
            this.btnKhachHang.AutoSizeLeftIcon = true;
            this.btnKhachHang.AutoSizeRightIcon = true;
            this.btnKhachHang.BackColor = System.Drawing.Color.Transparent;
            this.btnKhachHang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKhachHang.BackgroundImage")));
            this.btnKhachHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.ButtonText = "Khách hàng";
            this.btnKhachHang.ButtonTextMarginLeft = 0;
            this.btnKhachHang.ColorContrastOnClick = 45;
            this.btnKhachHang.ColorContrastOnHover = 45;
            this.btnKhachHang.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges18.BottomLeft = true;
            borderEdges18.BottomRight = true;
            borderEdges18.TopLeft = true;
            borderEdges18.TopRight = true;
            this.btnKhachHang.CustomizableEdges = borderEdges18;
            this.btnKhachHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKhachHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKhachHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKhachHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKhachHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKhachHang.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnKhachHang.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKhachHang.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnKhachHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnKhachHang.IconMarginLeft = 11;
            this.btnKhachHang.IconPadding = 10;
            this.btnKhachHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKhachHang.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnKhachHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKhachHang.IconSize = 25;
            this.btnKhachHang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.IdleBorderRadius = 30;
            this.btnKhachHang.IdleBorderThickness = 1;
            this.btnKhachHang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.IdleIconLeftImage = null;
            this.btnKhachHang.IdleIconRightImage = null;
            this.btnKhachHang.IndicateFocus = true;
            this.btnKhachHang.Location = new System.Drawing.Point(40, 316);
            this.btnKhachHang.Name = "btnKhachHang";
            this.btnKhachHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKhachHang.OnDisabledState.BorderRadius = 30;
            this.btnKhachHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnDisabledState.BorderThickness = 1;
            this.btnKhachHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKhachHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKhachHang.OnDisabledState.IconLeftImage = null;
            this.btnKhachHang.OnDisabledState.IconRightImage = null;
            this.btnKhachHang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.onHoverState.BorderRadius = 30;
            this.btnKhachHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.onHoverState.BorderThickness = 1;
            this.btnKhachHang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnKhachHang.onHoverState.IconLeftImage = null;
            this.btnKhachHang.onHoverState.IconRightImage = null;
            this.btnKhachHang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.OnIdleState.BorderRadius = 30;
            this.btnKhachHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnIdleState.BorderThickness = 1;
            this.btnKhachHang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnKhachHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.OnIdleState.IconLeftImage = null;
            this.btnKhachHang.OnIdleState.IconRightImage = null;
            this.btnKhachHang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnKhachHang.OnPressedState.BorderRadius = 30;
            this.btnKhachHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnPressedState.BorderThickness = 1;
            this.btnKhachHang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnKhachHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.OnPressedState.IconLeftImage = null;
            this.btnKhachHang.OnPressedState.IconRightImage = null;
            this.btnKhachHang.Size = new System.Drawing.Size(211, 58);
            this.btnKhachHang.TabIndex = 0;
            this.btnKhachHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnKhachHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKhachHang.TextMarginLeft = 0;
            this.btnKhachHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnKhachHang.UseDefaultRadiusAndThickness = true;
            this.btnKhachHang.Click += new System.EventHandler(this.btnKhachHang_Click);
            // 
            // btnNhanVien
            // 
            this.btnNhanVien.AllowAnimations = true;
            this.btnNhanVien.AllowMouseEffects = true;
            this.btnNhanVien.AllowToggling = true;
            this.btnNhanVien.AnimationSpeed = 200;
            this.btnNhanVien.AutoGenerateColors = false;
            this.btnNhanVien.AutoRoundBorders = false;
            this.btnNhanVien.AutoSizeLeftIcon = true;
            this.btnNhanVien.AutoSizeRightIcon = true;
            this.btnNhanVien.BackColor = System.Drawing.Color.Transparent;
            this.btnNhanVien.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNhanVien.BackgroundImage")));
            this.btnNhanVien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanVien.ButtonText = "Nhân viên";
            this.btnNhanVien.ButtonTextMarginLeft = 0;
            this.btnNhanVien.ColorContrastOnClick = 45;
            this.btnNhanVien.ColorContrastOnHover = 45;
            this.btnNhanVien.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.btnNhanVien.CustomizableEdges = borderEdges19;
            this.btnNhanVien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNhanVien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhanVien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhanVien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhanVien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNhanVien.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNhanVien.ForeColor = System.Drawing.Color.White;
            this.btnNhanVien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhanVien.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNhanVien.IconMarginLeft = 11;
            this.btnNhanVien.IconPadding = 10;
            this.btnNhanVien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNhanVien.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnNhanVien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNhanVien.IconSize = 25;
            this.btnNhanVien.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.IdleBorderRadius = 30;
            this.btnNhanVien.IdleBorderThickness = 1;
            this.btnNhanVien.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.IdleIconLeftImage = null;
            this.btnNhanVien.IdleIconRightImage = null;
            this.btnNhanVien.IndicateFocus = true;
            this.btnNhanVien.Location = new System.Drawing.Point(40, 240);
            this.btnNhanVien.Name = "btnNhanVien";
            this.btnNhanVien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhanVien.OnDisabledState.BorderRadius = 30;
            this.btnNhanVien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanVien.OnDisabledState.BorderThickness = 1;
            this.btnNhanVien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhanVien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhanVien.OnDisabledState.IconLeftImage = null;
            this.btnNhanVien.OnDisabledState.IconRightImage = null;
            this.btnNhanVien.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.onHoverState.BorderRadius = 30;
            this.btnNhanVien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanVien.onHoverState.BorderThickness = 1;
            this.btnNhanVien.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnNhanVien.onHoverState.IconLeftImage = null;
            this.btnNhanVien.onHoverState.IconRightImage = null;
            this.btnNhanVien.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.OnIdleState.BorderRadius = 30;
            this.btnNhanVien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanVien.OnIdleState.BorderThickness = 1;
            this.btnNhanVien.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnNhanVien.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNhanVien.OnIdleState.IconLeftImage = null;
            this.btnNhanVien.OnIdleState.IconRightImage = null;
            this.btnNhanVien.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhanVien.OnPressedState.BorderRadius = 30;
            this.btnNhanVien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanVien.OnPressedState.BorderThickness = 1;
            this.btnNhanVien.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnNhanVien.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNhanVien.OnPressedState.IconLeftImage = null;
            this.btnNhanVien.OnPressedState.IconRightImage = null;
            this.btnNhanVien.Size = new System.Drawing.Size(211, 58);
            this.btnNhanVien.TabIndex = 0;
            this.btnNhanVien.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNhanVien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNhanVien.TextMarginLeft = 0;
            this.btnNhanVien.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNhanVien.UseDefaultRadiusAndThickness = true;
            this.btnNhanVien.Click += new System.EventHandler(this.btnNhanVien_Click);
            // 
            // panelTop
            // 
            this.panelTop.Controls.Add(this.bunifuLabel1);
            this.panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Location = new System.Drawing.Point(293, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new System.Drawing.Size(1033, 79);
            this.panelTop.TabIndex = 1;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(1033, 79);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "QUẢN LÝ CỬA HÀNG CAMERA ADC";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // panelBottom
            // 
            this.panelBottom.BackColor = System.Drawing.Color.Black;
            this.panelBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBottom.Location = new System.Drawing.Point(293, 982);
            this.panelBottom.Name = "panelBottom";
            this.panelBottom.Size = new System.Drawing.Size(1033, 45);
            this.panelBottom.TabIndex = 2;
            // 
            // panelMid
            // 
            this.panelMid.Cursor = System.Windows.Forms.Cursors.Default;
            this.panelMid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMid.ForeColor = System.Drawing.Color.Black;
            this.panelMid.Location = new System.Drawing.Point(293, 79);
            this.panelMid.Name = "panelMid";
            this.panelMid.Size = new System.Drawing.Size(1033, 903);
            this.panelMid.TabIndex = 3;
            // 
            // btnQLHoaDon
            // 
            this.btnQLHoaDon.AllowAnimations = true;
            this.btnQLHoaDon.AllowMouseEffects = true;
            this.btnQLHoaDon.AllowToggling = true;
            this.btnQLHoaDon.AnimationSpeed = 200;
            this.btnQLHoaDon.AutoGenerateColors = false;
            this.btnQLHoaDon.AutoRoundBorders = false;
            this.btnQLHoaDon.AutoSizeLeftIcon = true;
            this.btnQLHoaDon.AutoSizeRightIcon = true;
            this.btnQLHoaDon.BackColor = System.Drawing.Color.Transparent;
            this.btnQLHoaDon.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnQLHoaDon.BackgroundImage")));
            this.btnQLHoaDon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLHoaDon.ButtonText = "Hóa Đơn Bán";
            this.btnQLHoaDon.ButtonTextMarginLeft = 0;
            this.btnQLHoaDon.ColorContrastOnClick = 45;
            this.btnQLHoaDon.ColorContrastOnHover = 45;
            this.btnQLHoaDon.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btnQLHoaDon.CustomizableEdges = borderEdges20;
            this.btnQLHoaDon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnQLHoaDon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLHoaDon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLHoaDon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLHoaDon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnQLHoaDon.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnQLHoaDon.ForeColor = System.Drawing.Color.White;
            this.btnQLHoaDon.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLHoaDon.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnQLHoaDon.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnQLHoaDon.IconMarginLeft = 11;
            this.btnQLHoaDon.IconPadding = 10;
            this.btnQLHoaDon.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnQLHoaDon.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnQLHoaDon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnQLHoaDon.IconSize = 25;
            this.btnQLHoaDon.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.IdleBorderRadius = 30;
            this.btnQLHoaDon.IdleBorderThickness = 1;
            this.btnQLHoaDon.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.IdleIconLeftImage = null;
            this.btnQLHoaDon.IdleIconRightImage = null;
            this.btnQLHoaDon.IndicateFocus = true;
            this.btnQLHoaDon.Location = new System.Drawing.Point(40, 791);
            this.btnQLHoaDon.Name = "btnQLHoaDon";
            this.btnQLHoaDon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLHoaDon.OnDisabledState.BorderRadius = 30;
            this.btnQLHoaDon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLHoaDon.OnDisabledState.BorderThickness = 1;
            this.btnQLHoaDon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLHoaDon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLHoaDon.OnDisabledState.IconLeftImage = null;
            this.btnQLHoaDon.OnDisabledState.IconRightImage = null;
            this.btnQLHoaDon.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.onHoverState.BorderRadius = 30;
            this.btnQLHoaDon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLHoaDon.onHoverState.BorderThickness = 1;
            this.btnQLHoaDon.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnQLHoaDon.onHoverState.IconLeftImage = null;
            this.btnQLHoaDon.onHoverState.IconRightImage = null;
            this.btnQLHoaDon.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.OnIdleState.BorderRadius = 30;
            this.btnQLHoaDon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLHoaDon.OnIdleState.BorderThickness = 1;
            this.btnQLHoaDon.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(83)))), ((int)(((byte)(66)))), ((int)(((byte)(194)))));
            this.btnQLHoaDon.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnQLHoaDon.OnIdleState.IconLeftImage = null;
            this.btnQLHoaDon.OnIdleState.IconRightImage = null;
            this.btnQLHoaDon.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnQLHoaDon.OnPressedState.BorderRadius = 30;
            this.btnQLHoaDon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLHoaDon.OnPressedState.BorderThickness = 1;
            this.btnQLHoaDon.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(106)))), ((int)(((byte)(206)))));
            this.btnQLHoaDon.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnQLHoaDon.OnPressedState.IconLeftImage = null;
            this.btnQLHoaDon.OnPressedState.IconRightImage = null;
            this.btnQLHoaDon.Size = new System.Drawing.Size(211, 58);
            this.btnQLHoaDon.TabIndex = 0;
            this.btnQLHoaDon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnQLHoaDon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnQLHoaDon.TextMarginLeft = 0;
            this.btnQLHoaDon.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnQLHoaDon.UseDefaultRadiusAndThickness = true;
            this.btnQLHoaDon.Click += new System.EventHandler(this.btnQLHoaDon_Click);
            // 
            // frmMeNu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1326, 1027);
            this.ControlBox = false;
            this.Controls.Add(this.panelMid);
            this.Controls.Add(this.panelBottom);
            this.Controls.Add(this.panelTop);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmMeNu";
            this.Text = "FrmMeNu";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panelTop.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panelTop;
        private System.Windows.Forms.Panel panelBottom;
        private System.Windows.Forms.Panel panelMid;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNhanVien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThoat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThongKe;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNhapHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBanHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSanPham;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLoaiSP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNhaCungCap;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKhachHang;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnQLHoaDon;
    }
}

